apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml

images:
  - name: quay.io/akurinnoy/config-sync-mcp
    newName: quay.io/akurinnoy/config-sync-mcp
    newTag: next
